### ISSUE TITLE
New Version of Scapy Breaks Tool

### ISSUE THREAD

**Issue by man715** [MWR-CyberSec/PXEThief#10]
The new version of scapy (version 2.6.0) breaks the tool and causes the below error:

![image](https://github.com/user-attachments/assets/e8547861-a85f-4e7e-b5a8-eaeafb6be9c2)

**Comment by cgpw** [comment]
I think you can fix it by changing `fam,clientMacAddress = get_if_raw_hwaddr(conf.iface)` to `clientMacAddress = get_if_hwaddr(conf.iface)`

I don't think the `fam` variable is used for anything.

**Comment by 7MinSec** [comment]
For me that just changed the error (I'm using option `1`):

```
Sending initial DHCP Discover to find PXE boot server...

Begin emission
.
Finished sending 1 packets
..*
Received 4 packets, got 1 answers, remaining 0 packets
Traceback (most recent call last):
  File "pxethief.py", line 855, in <module>
    get_pxe_files(None)
    ~~~~~~~~~~~~~^^^^^^
  File "pxethief.py", line 279, in get_pxe_files
    tftp_server_ip = find_pxe_server()
  File "pxethief.py", line 193, in find_pxe_server
    tftp_server = validate_ip_or_resolve_hostname(tftp_server.strip())
                                                  ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

Could be unrelated though, and this might mean no target server was found?

**Comment by abs0lute-sra** [comment]
I had success with the initial error using `get_if_hwaddr `instead of `get_if_raw_hwaddr`. They must've changed the available function in the newer versions of scapy. https://scapy.readthedocs.io/en/latest/routing.html#get-the-mac-of-an-interface

**Comment by 7MinSec** [comment]
On a recent test I made the `get_if_hwaddr` (instead of `get_if_raw_hwaddr`) change that was suggested by @abs0lute-sra , as well as the `fam` change that @cgpw suggested.  

At next pxethief run, I was still getting this error I reported earlier in the thread:

```
Sending initial DHCP Discover to find PXE boot server...

Begin emission
.
Finished sending 1 packets
..*
Received 4 packets, got 1 answers, remaining 0 packets
Traceback (most recent call last):
  File "pxethief.py", line 855, in <module>
    get_pxe_files(None)
    ~~~~~~~~~~~~~^^^^^^
  File "pxethief.py", line 279, in get_pxe_files
    tftp_server_ip = find_pxe_server()
  File "pxethief.py", line 193, in find_pxe_server
    tftp_server = validate_ip_or_resolve_hostname(tftp_server.strip())
                                                  ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

I then enumerated the environment with pxethiefy and that tool told me there were 4 possible servers offering PXE.  When I did targeted attacks on them with pxethiefy, only ONE actually responded with a valid file and I end up with a variables.xml and LONGID-SMSTSMediaPFX.pfx file, which ties into another issue I have open [here](https://github.com/MWR-CyberSec/PXEThief/issues/12).

**Comment by foofus-sph1nx** [comment]
I was able to fix it by downgrading the version of scapy.

pip uninstall scapy
pip install scapy==2.5.0

**Comment by bouj33boy** [comment]
It works with no issues if you:

- "get_if_hwaddr (instead of get_if_raw_hwaddr) change that was suggested by @abs0lute-sra , as well as the "fam" change that @cgpw suggested"

- Install the most current version of Scapy:  [v2.6.1](https://github.com/secdev/scapy/releases/tag/v2.6.1)
